# Generated by Django 4.2.3 on 2023-07-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_topic_room_user_alter_room_discription_messages_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="user",
            new_name="host",
        ),
    ]
